"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class image_metadata_t(object):
    """ this was copied from libbot, bot_core lcmtypes package """

    __slots__ = ["key", "n", "value"]

    __typenames__ = ["string", "int32_t", "byte"]

    __dimensions__ = [None, None, ["n"]]

    def __init__(self):
        self.key = ""
        """ LCM Type: string """
        self.n = 0
        """ LCM Type: int32_t """
        self.value = b""
        """ LCM Type: byte[n] """

    def encode(self):
        buf = BytesIO()
        buf.write(image_metadata_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __key_encoded = self.key.encode('utf-8')
        buf.write(struct.pack('>I', len(__key_encoded)+1))
        buf.write(__key_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">i", self.n))
        buf.write(bytearray(self.value[:self.n]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != image_metadata_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return image_metadata_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = image_metadata_t()
        __key_len = struct.unpack('>I', buf.read(4))[0]
        self.key = buf.read(__key_len)[:-1].decode('utf-8', 'replace')
        self.n = struct.unpack(">i", buf.read(4))[0]
        self.value = buf.read(self.n)
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if image_metadata_t in parents: return 0
        tmphash = (0x4d25b1a682bbfdc7) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if image_metadata_t._packed_fingerprint is None:
            image_metadata_t._packed_fingerprint = struct.pack(">Q", image_metadata_t._get_hash_recursive([]))
        return image_metadata_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", image_metadata_t._get_packed_fingerprint())[0]

